-- ---------------------------------------------------------
-- GFM Record Management System - Complete Database Schema
-- ---------------------------------------------------------

-- 1. Enable UUID extension
create extension if not exists "uuid-ossp";

-- 2. Clean up existing tables (ORDER MATTERS due to foreign keys)
-- Using CASCADE to ensure all dependent objects (policies, views, foreign keys) are removed
drop table if exists academic_records cascade;
drop table if exists achievements cascade;
drop table if exists student_activities cascade;
drop table if exists technical_activities cascade; -- Legacy table cleanup
drop table if exists non_technical_activities cascade; -- Legacy table cleanup
drop table if exists internships cascade;
drop table if exists fee_payments cascade;
drop table if exists students cascade;
drop table if exists courses_def cascade;
drop table if exists profiles cascade;

-- 3. Create PROFILES Table (Links to Auth)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text unique not null,
  role text not null check (role in ('student', 'teacher', 'admin')),
  prn text unique, -- For students
  full_name text,
  department text,
  password text, -- Plain text password for easy lookup (Unified Terminology)
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 4. Create STUDENTS Table (Detailed Profile)
create table students (
  prn text primary key,
  full_name text not null,
  gender text,
  religion text,
  category text,
  caste text,
  dob date,
  branch text default 'CSE',
  division text,
  year_of_study text,
  phone text,
  email text,
  aadhar text,
  permanent_address text,
  pincode text,
  temporary_address text,
  
  -- Parent Details
  father_name text,
  mother_name text,
  father_occupation text,
  mother_occupation text,
  annual_income text,
  father_phone text,
  mother_phone text,
  
  -- Previous Education
  ssc_school text,
  ssc_marks text,
  ssc_max_marks text,
  ssc_percentage text,
  ssc_year text,
  
  hsc_college text,
  hsc_marks text,
  hsc_max_marks text,
  hsc_percentage text,
  hsc_year text,
  
  diploma_college text,
  diploma_marks text,
  diploma_max_marks text,
  diploma_percentage text,
  diploma_year text,
  diploma_branch text,
  diploma_board text,
  diploma_state text,
  diploma_city text,
  diploma_cgpa text,
  diploma_passing_month text,
  
  -- Admission Details
  admission_type text,
  jee_percentile text,
  mht_cet_percentile text,
  
  photo_uri text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 5. Create COURSES_DEF Table (Course Definitions)
create table courses_def (
  id bigint generated by default as identity primary key,
  course_code text not null,
  course_name text not null,
  department text default 'CSE',
  semester int not null,
  credits int default 0,
  ise_max int default 0,
  mse_max int default 0,
  ese_max int default 0,
  created_at timestamptz default now()
);

-- 6. Create ACADEMIC_RECORDS Table
create table academic_records (
  id bigint generated by default as identity primary key,
  prn text references students(prn) on delete cascade not null,
  course_def_id bigint references courses_def(id) on delete cascade not null,
  semester int not null,
  ise_marks decimal default 0,
  mse_marks decimal default 0,
  ese_marks decimal default 0,
  total_marks decimal default 0,
  grade text,
  sgpa decimal,
  cgpa decimal,
  academic_year text,
  created_at timestamptz default now()
);

-- 7. Create ACHIEVEMENTS Table
create table achievements (
  id bigint generated by default as identity primary key,
  prn text references students(prn) on delete cascade not null,
  achievement_name text not null,
  type text, -- Technical, Non-Technical, etc.
  achievement_date date,
  description text,
  semester int,
  certificate_uri text,
  verification_status text default 'Pending', -- Pending, Approved, Rejected
  verified_by text,
  created_at timestamptz default now()
);

-- 8. Create STUDENT_ACTIVITIES Table (Co-curricular, Extra, Courses)
create table student_activities (
  id bigint generated by default as identity primary key,
  prn text references students(prn) on delete cascade not null,
  activity_name text not null,
  type text not null, -- 'Co-curricular', 'Extra-curricular', 'Courses'
  activity_date date,
  description text,
  semester int,
  certificate_uri text,
  platform text, -- For Courses
  duration text, -- For Courses
  verification_status text default 'Pending',
  verified_by text,
  created_at timestamptz default now()
);

-- 9. Create INTERNSHIPS Table
create table internships (
  id bigint generated by default as identity primary key,
  prn text references students(prn) on delete cascade not null,
  company_name text not null,
  role text,
  semester int,
  internship_type text, -- 'Paid', 'Unpaid'
  start_date date,
  end_date date,
  duration int, -- in days or weeks
  stipend decimal,
  description text,
  certificate_uri text,
  verification_status text default 'Pending',
  verified_by text,
  created_at timestamptz default now()
);

-- 10. Create FEE_PAYMENTS Table
create table fee_payments (
  id bigint generated by default as identity primary key,
  prn text references students(prn) on delete cascade not null,
  academic_year text not null,
  category text,
  total_fee decimal,
  amount_paid decimal,
  remaining_balance decimal,
  payment_date date,
  payment_mode text,
  receipt_uri text,
  verification_status text default 'Pending',
  verified_by text,
  created_at timestamptz default now()
);

-- 11. Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table students enable row level security;
alter table courses_def enable row level security;
alter table academic_records enable row level security;
alter table achievements enable row level security;
alter table student_activities enable row level security;
alter table internships enable row level security;
alter table fee_payments enable row level security;

-- 12. Create Policies (Permissive for development - adjust for production)
-- Allow public read/write access for now to ensure app works without complex auth setup immediately
-- Ideally, you restrict this based on auth.uid()

create policy "Enable all access for all users" on profiles for all using (true) with check (true);
create policy "Enable all access for all users" on students for all using (true) with check (true);
create policy "Enable all access for all users" on courses_def for all using (true) with check (true);
create policy "Enable all access for all users" on academic_records for all using (true) with check (true);
create policy "Enable all access for all users" on achievements for all using (true) with check (true);
create policy "Enable all access for all users" on student_activities for all using (true) with check (true);
create policy "Enable all access for all users" on internships for all using (true) with check (true);
create policy "Enable all access for all users" on fee_payments for all using (true) with check (true);

-- 13. Create Storage Buckets (Optional - You usually do this in Supabase UI)
-- This is just a reminder, SQL cannot always create storage buckets directly depending on permissions.
-- Buckets needed: 'document-uploads' (or similar based on your code)
